services:
    jet:
      image: hazelcast/hazelcast-jet-enterprise:4.3.1
      environment:
        - JET_LICENSE_KEY 
        - JAVA_OPTS=-Dhazelcast.config=/etc/hazelcast/hazelcast.yaml
      volumes:
        - "./config:/etc/hazelcast"
      
    jetmc: 
      image: hazelcast/hazelcast-jet-management-center:4.3.1
      environment: 
        - MC_LICENSE_KEY 
        - MC_CLIENT_CONFIG=/etc/hazelcast/hazelcast-client.xml
      volumes:
        - "./config:/etc/hazelcast"
      ports:
        - "8081:8081"

# secrets:
#   jet-license-key:
#     file: .jet-license-key
