---
- hosts: all
  vars:
    ansible_ssh_user: ec2-user
  tasks:
    - name: install required software 
      become: yes
      yum: 
        name: ['java-1.8.0-openjdk-devel.x86_64', 'nc', 'git','lsof']
    
    - name: disable iptables
      become: yes
      service: 
        name: iptables
        enabled: no 
        state: stopped
    
    - name: download and unpack GemFire 9.3 
      become: no
      unarchive:
        remote_src: yes
        src: http://download.pivotal.com.s3.amazonaws.com/gemfire/9.3.0/pivotal-gemfire-9.3.0.zip
        dest: /runtime
        owner: ec2-user
        group: ec2-user
        
    - name: create GemFire symbolic link
      become: no 
      file: 
        path: /runtime/gemfire 
        src: /runtime/pivotal-gemfire-9.3.0
        state: link
        owner: ec2-user 
        group: ec2-user 
        
    - name: download and unpack Maven
      become: no
      unarchive:
        remote_src: yes
        src:  http://apache.cs.utah.edu/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz
        dest: /runtime
        owner: ec2-user
        group: ec2-user
        
    - name: create Maven symbolic link
      become: no 
      file: 
        path: /runtime/maven 
        src: /runtime/apache-maven-3.6.0
        remote_src: yes
        state: link
        owner: ec2-user 
        group: ec2-user 

    - name: configure the bash profile 
      become: no 
      copy: 
        src: setuptasks/ConfigureProfile/bash_profile 
        dest: /home/ec2-user/.bash_profile 
        owner: ec2-user 
        group: ec2-user 
        
    - name: configure maven 
      become: no
      copy:
        src: setuptasks/ConfigureMaven/settings.xml 
        dest: /home/ec2-user/.m2/
        owner: ec2-user 
        group: ec2-user 
        
    - name: git clone  gemfire-manager 
      become: no
      git:
        repo: https://github.com/Pivotal-Data-Engineering/gemfire-manager
        clone: yes 
        version: 2.1 
        recursive: no 
        depth: 1
        dest: /runtime/gemfire-manager
        
    - name: setup the cluster working directories
      become: no
      copy: 
        src: cluster.json 
        dest: /runtime/gem_cluster_1/
        owner: ec2-user 
        group: ec2-user 

    - name: copy gemfire-manager scripts to cluster working directory 
      become: no
      copy: 
        src: /runtime/gemfire-manager/{{ item }}
        remote_src: yes
        dest: /runtime/gem_cluster_1/
        owner: ec2-user 
        group: ec2-user 
      loop: ['gf.py', 'cluster.py', 'clusterdef.py', 'gemprops.py']
      
    - name: git clone  gemfire-toolkit
      become: no
      git:
        repo: https://github.com/Pivotal-Data-Engineering/gemfire-toolkit
        clone: yes 
        version: gemfire-toolkit-2.1 
        recursive: no 
        depth: 1
        dest: /runtime/gemfire-toolkit 
        
    - name: build gemfire-toolkit 
      become: no
      command: /runtime/maven/bin/mvn package
      args:
        chdir: /runtime/gemfire-toolkit
      
    - name: install gemfire-toolkit
      become: no       
      unarchive:
        remote_src: yes
        src:  /runtime/gemfire-toolkit/target/gemfire-toolkit-2.1-runtime.tar.gz
        dest: /runtime/gem_cluster_1 
        owner: ec2-user
        group: ec2-user
